#!/bin/bash
# WebSocket認証エラー（/auth 404）解決手順
# 実行日時: 2025年8月5日

echo "=== WebSocket認証エラー解決手順 ==="
echo "実行開始: $(date)"

echo ""
echo "🔧 手順1: DCV Server設定の修正（Agent側: 10.150.248.180）"
echo "以下のコマンドをAgent側で実行してください："
echo ""
echo "# 1. Broker証明書の存在確認"
echo "ssh -i \"tom.pem\" ubuntu@10.213.66.188 \"sudo ls -la /etc/dcv-session-manager-agent/broker_cert.pem\""
echo ""
echo "# 2. 証明書が存在しない場合、Gateway側からコピー"
echo "echo '証明書コピーが必要な場合:'"
echo "ssh -i \"tom.pem\" ec2-user@10.213.66.188 -p 50000 \"sudo cat /var/lib/dcvsmbroker/security/dcvsmbroker_ca.pem\" > broker_cert.pem"
echo "scp -i \"tom.pem\" broker_cert.pem ubuntu@10.213.66.188:/tmp/"
echo "ssh -i \"tom.pem\" ubuntu@10.213.66.188 \"sudo mv /tmp/broker_cert.pem /etc/dcv-session-manager-agent/broker_cert.pem\""
echo "ssh -i \"tom.pem\" ubuntu@10.213.66.188 \"sudo chown dcv:dcv /etc/dcv-session-manager-agent/broker_cert.pem\""
echo ""
echo "# 3. DCV Server設定ファイルのバックアップ"
echo "ssh -i \"tom.pem\" ubuntu@10.213.66.188 \"sudo cp /etc/dcv/dcv.conf /etc/dcv/dcv.conf.backup-$(date +%Y%m%d-%H%M%S)\""
echo ""
echo "# 4. 修正されたDCV Server設定の適用"
echo "cat << 'EOF' > dcv_server_fixed.conf"
echo "[security]"
echo "# Session Manager統合用の認証設定"
echo "auth-token-verifier = \"https://10.150.248.162:8445/agent/validate-authentication-token\""
echo "ca-file = \"/etc/dcv-session-manager-agent/broker_cert.pem\""
echo ""
echo "# Origin制御設定（HTTP 407エラー解決済み）"
echo "allowed-http-host-regex = \"^(10\\.213\\.66\\.188|vpce-.*\\.vpce\\.amazonaws\\.com)$\""
echo "allowed-ws-origin-regex = \"^https://(10\\.213\\.66\\.188|vpce-.*\\.vpce\\.amazonaws\\.com)(:[0-9]+)?$\""
echo ""
echo "[session-management]"
echo "# セッション管理設定"
echo "create-session = true"
echo ""
echo "[display]"
echo "# ディスプレイ設定"
echo "target-fps = 25"
echo ""
echo "[connectivity]"
echo "# 接続設定"
echo "enable-quic-frontend = true"
echo ""
echo "[log]"
echo "# ログ設定"
echo "level = \"info\""
echo "EOF"
echo ""
echo "scp -i \"tom.pem\" dcv_server_fixed.conf ubuntu@10.213.66.188:/tmp/"
echo "ssh -i \"tom.pem\" ubuntu@10.213.66.188 \"sudo mv /tmp/dcv_server_fixed.conf /etc/dcv/dcv.conf\""
echo ""

echo "🔧 手順2: DCV Serverサービスの再起動"
echo "ssh -i \"tom.pem\" ubuntu@10.213.66.188 \"sudo systemctl stop dcvserver\""
echo "ssh -i \"tom.pem\" ubuntu@10.213.66.188 \"sudo systemctl start dcvserver\""
echo "ssh -i \"tom.pem\" ubuntu@10.213.66.188 \"sudo systemctl status dcvserver --no-pager\""
echo ""

echo "🔧 手順3: Session Manager Agentの再起動"
echo "ssh -i \"tom.pem\" ubuntu@10.213.66.188 \"sudo systemctl restart dcv-session-manager-agent\""
echo "ssh -i \"tom.pem\" ubuntu@10.213.66.188 \"sudo systemctl status dcv-session-manager-agent --no-pager\""
echo ""

echo "🔧 手順4: 設定確認"
echo "# DCV設定ファイルの確認"
echo "ssh -i \"tom.pem\" ubuntu@10.213.66.188 \"sudo cat /etc/dcv/dcv.conf\""
echo ""
echo "# 証明書ファイルの確認"
echo "ssh -i \"tom.pem\" ubuntu@10.213.66.188 \"sudo ls -la /etc/dcv-session-manager-agent/broker_cert.pem\""
echo ""

echo "🔧 手順5: 接続テスト"
echo "# Session Resolver動作確認"
echo "ssh -i \"tom.pem\" ec2-user@10.213.66.188 -p 50000 \"curl -k -X POST 'https://127.0.0.1:8447/resolveSession?sessionId=console&transport=HTTP&clientIpAddress=10.213.66.188'\""
echo ""
echo "# VPC Endpoint経由でのHTTP接続確認"
echo "curl --noproxy '*' -k https://vpce-02c333708db2e72b7-o2x6rrvy.vpce-svc-039cee5d9ee693914.ap-northeast-1.vpce.amazonaws.com:8443/?sessionId=console"
echo ""
echo "# Agent直接接続（50001ポート）での確認"
echo "curl --noproxy '*' -k https://10.213.66.188:50001/?sessionId=console"
echo ""

echo "🔧 手順6: ブラウザテスト"
echo "以下のURLでブラウザテストを実行："
echo "1. VPC Endpoint経由: https://vpce-02c333708db2e72b7-o2x6rrvy.vpce-svc-039cee5d9ee693914.ap-northeast-1.vpce.amazonaws.com:8443/?sessionId=console"
echo "2. Agent直接接続: https://10.213.66.188:50001/?sessionId=console"
echo ""
echo "期待される結果:"
echo "- DCVログイン画面が表示される"
echo "- WebSocket接続エラー（/auth 404）が解消される"
echo "- Ubuntuデスクトップが表示される"
echo ""

echo "🔧 手順7: トラブルシューティング用ログ確認"
echo "# DCV Serverログ"
echo "ssh -i \"tom.pem\" ubuntu@10.213.66.188 \"sudo journalctl -u dcvserver -n 50 --no-pager\""
echo ""
echo "# Session Manager Agentログ"
echo "ssh -i \"tom.pem\" ubuntu@10.213.66.188 \"sudo journalctl -u dcv-session-manager-agent -n 50 --no-pager\""
echo ""
echo "# Connection Gatewayログ"
echo "ssh -i \"tom.pem\" ec2-user@10.213.66.188 -p 50000 \"sudo journalctl -u dcv-connection-gateway -n 50 --no-pager\""
echo ""

echo "実行完了: $(date)"
echo "=== WebSocket認証エラー解決手順完了 ==="